### ISSUE TITLE
Scikit-learn, tensorflow, keras dependencies

### ISSUE THREAD

**Issue by mfe7** [ethz-asl/voxblox-plusplus#58]
Hi - thanks for the help getting things to compile! When running the node I ran into some dependency issues.

When running the launch file:
```
roslaunch gsm_node scenenn_dataset.launch bag_file:=/path/to/scenenn_231.bag
```

I got the error:
```
Traceback (most recent call last):
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/scripts/mask_rcnn_node.py", line 13, in <module>
    from mask_rcnn_ros import coco
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/src/mask_rcnn_ros/coco.py", line 49, in <module>
    import utils
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/src/mask_rcnn_ros/utils.py", line 17, in <module>
    import skimage.color
ImportError: No module named skimage.color
```
which was resolved by doing `pip install scikit-image`.

I then got the error:
```
Traceback (most recent call last):
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/scripts/mask_rcnn_node.py", line 204, in <module>
    main()
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/scripts/mask_rcnn_node.py", line 199, in main
    node = MaskRCNNNode()
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/scripts/mask_rcnn_node.py", line 61, in __init__
    config=config)
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/src/mask_rcnn_ros/model.py", line 1768, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/src/mask_rcnn_ros/model.py", line 1951, in build
    config.POOL_SIZE, config.NUM_CLASSES)
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/src/mask_rcnn_ros/model.py", line 904, in fpn_classifier_graph
    name="roi_align_classifier")([rois] + feature_maps)
  File "/mnt/ubuntu_extra_ssd2/code/voxbox_ws/venv/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/mnt/ubuntu_extra_ssd2/code/voxbox_ws/venv/local/lib/python2.7/site-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/src/mask_rcnn_ros/model.py", line 365, in call
    roi_level = log2_graph(tf.sqrt(h * w) / (224.0 / tf.sqrt(image_area)))
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/src/mask_rcnn_ros/model.py", line 320, in log2_graph
    return tf.log(x) / tf.log(2.0)
AttributeError: 'module' object has no attribute 'log'
```
which seemed to be resolved by doing `pip install tensorflow-gpu==1.14.0` but I am unsure if this is the right version to downgrade to?

Then I got:
```
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/scripts/mask_rcnn_node.py", line 204, in <module>
    main()
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/scripts/mask_rcnn_node.py", line 199, in main
    node = MaskRCNNNode()
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/scripts/mask_rcnn_node.py", line 68, in __init__
    self._model.load_weights(model_path, by_name=True)
  File "/home/mfe/code/voxbox_ws/src/mask_rcnn_ros/src/mask_rcnn_ros/model.py", line 2037, in load_weights
    topology.load_weights_from_hdf5_group_by_name(f, layers)
AttributeError: 'module' object has no attribute 'load_weights_from_hdf5_group_by_name'
```

I then downgraded keras:
```
pip install 'keras==2.1.6' --force-reinstall
```

Now, there are no errors and the bag is playing and 4 blank windows appeared. But the windows remain blank.

**Comment by margaritaG** [comment]
@mfe7 All the necessary requirements for compiling the voxblox++ packages should be listed [here](https://github.com/ethz-asl/voxblox-plusplus/wiki/Installation-on-Ubuntu#requirements). 

I have never tested with tensorflow-gpu==1.14.0 (I am using tensorflow-gpu1.6.0 with Keras 2.1.6) but I do not see why it would not work. 

If after your roslaunch voxblox++ is just hanging there with 4 blank windows, it means it has not received any segment yet to integrate. Something worth checking is whether the two segmentation nodes (mask_rcnn and depth_segmentation_node) are running and operational.
1. After your roslaunch, do you see something similar to:
```
process[mask_rcnn-2]: started with pid [9092]
process[depth_segmentation_node-3]: started with pid [9107]
```

2. Has the mask_rcnn node found the GPU to use? On my machine I see the following output:
```
Using TensorFlow backend.
2020-01-06 14:59:59.595586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: Quadro M2200 major: 5 minor: 2 memoryClockRate(GHz): 1.036
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 2.25GiB
2020-01-06 14:59:59.595602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
 done.

2020-01-06 15:00:00.349413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1946 MB memory) -> physical GPU (device: 0, name: Quadro M2200, pci bus id: 0000:01:00.0, compute capability: 5.2)

```
3. Check that mask_rcnn is actually publishing segmentation results via `$ rostopic hz /mask_rcnn/result`

Give this a try and let me know if this helped you investigate the issue.

**Comment by margaritaG** [comment]
Closing due to inactivity, please reopen if the issue persists.
