### ISSUE TITLE
helloBasic usage

### ISSUE THREAD

**Issue by resplendent-star** [ethz-asl/voxblox-plusplus#73]

**Comment by resplendent-star** [comment]
this is the file structure of my PC
![data](https://user-images.githubusercontent.com/41502003/79038873-7f47ff80-7c0f-11ea-9d94-312a95fa50c6.png)

when I   use  command:
roslaunch gsm_node scenenn_dataset.launch bag_file:=/home/lzw/dataset

I get:
---------------------------------------------------------------------------
[ INFO] [1586592659.707760011]: Opening /home/lzw/dataset
[FATAL] [1586592659.717310842]: Error reading version line

Voxblox++ Copyright (C) 2016-2020 ASL, ETH Zurich.

I0411 16:10:59.779852  2111 depth_segmentation_node.cpp:641] Starting depth segmentation ... 
Traceback (most recent call last):
  File "/home/lzw/resplendent_code/voxblox_pp_ws/src/mask_rcnn_ros/scripts/mask_rcnn_node.py", line 5, in <module>
    import cv2
ImportError: /home/lzw/resplendent_code/voxblox_pp_ws/devel/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type
[mask_rcnn-2] process has died [pid 2109, exit code 1, cmd /home/lzw/resplendent_code/voxblox_pp_ws/src/mask_rcnn_ros/scripts/mask_rcnn_node.py ~input:=rgb_image_sub_topic __name:=mask_rcnn __log:=/home/lzw/.ros/log/f9f6fb30-7bcb-11ea-b029-d45d640018a4/mask_rcnn-2.log].
log file: /home/lzw/.ros/log/f9f6fb30-7bcb-11ea-b029-d45d640018a4/mask_rcnn-2*.log
[bag-5] process has died [pid 2125, exit code 1, cmd /opt/ros/melodic/lib/rosbag/play --delay 5 -r 0.2 /home/lzw/dataset __name:=bag __log:=/home/lzw/.ros/log/f9f6fb30-7bcb-11ea-b029-d45d640018a4/bag-5.log].
log file: /home/lzw/.ros/log/f9f6fb30-7bcb-11ea-b029-d45d640018a4/bag-5*.log
I0411 16:10:59.930982  2111 depth_segmentation.cpp:289] Dynamic Reconfigure Request.




and  if i use command :
roslaunch gsm_node scenenn_dataset.launch bag_file:=/home/lzw/dataset/scenenn_231.bag

-------------------------------------------------------------------------------
I get 
process[bag-5]: started with pid [2283]
[ INFO] [1586592696.669478214]: Opening /home/lzw/dataset/scenenn_231.bag
[FATAL] [1586592696.678917545]: Error reading from file: wanted 4 bytes, read 0 bytes

Voxblox++ Copyright (C) 2016-2020 ASL, ETH Zurich.

I0411 16:11:36.738395  2259 depth_segmentation_node.cpp:641] Starting depth segmentation ... 
Traceback (most recent call last):
  File "/home/lzw/resplendent_code/voxblox_pp_ws/src/mask_rcnn_ros/scripts/mask_rcnn_node.py", line 5, in <module>
    import cv2
ImportError: /home/lzw/resplendent_code/voxblox_pp_ws/devel/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type
[mask_rcnn-2] process has died [pid 2258, exit code 1, cmd /home/lzw/resplendent_code/voxblox_pp_ws/src/mask_rcnn_ros/scripts/mask_rcnn_node.py ~input:=rgb_image_sub_topic __name:=mask_rcnn __log:=/home/lzw/.ros/log/0ff95522-7bcc-11ea-b029-d45d640018a4/mask_rcnn-2.log].
log file: /home/lzw/.ros/log/0ff95522-7bcc-11ea-b029-d45d640018a4/mask_rcnn-2*.log
I0411 16:11:36.889755  2259 depth_segmentation.cpp:289] Dynamic Reconfigure Request.
[bag-5] process has died [pid 2283, exit code 1, cmd /opt/ros/melodic/lib/rosbag/play --delay 5 -r 0.2 /home/lzw/dataset/scenenn_231.bag __name:=bag __log:=/home/lzw/.ros/log/0ff95522-7bcc-11ea-b029-d45d640018a4/bag-5.log].
log file: /home/lzw/.ros/log/0ff95522-7bcc-11ea-b029-d45d640018a4/bag-5*.log
^C[gsm_node-4] killing on exit
